config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'prototypes/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "prototypes#index"
  # resources :prototypes, only: [:index, :new, :create, :show, :edit, :update, :destroy]
  resources :prototypes
  # resources :comments, only: :create
  resources :prototypes do
    resources :comments, only: [:create]
  end
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  # バリデーション
  validates :text, presence: true # テキスト
  # アソシエーション
  belongs_to :user
  belongs_to :prototype
end

app/models/prototype.rb
class Prototype < ApplicationRecord
  # バリデーション
  validates :title,      presence: true # プロトタイプの名称
  validates :catch_copy, presence: true # キャッチコピー
  validates :concept,    presence: true # コンセプト
  validates :image,      presence: true # プロトタイプの画像1枚
  # アソシエーション
  belongs_to :user
  # validates :user_id presence: true ←不要
  has_many :comments, dependent: :destroy # prototypeが削除された場合、commentsも削除
  has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # バリデーション
  validates :name,       presence: true # ユーザー名
  validates :profile,    presence: true # プロフィール
  validates :occupation, presence: true # 所属
  validates :position,   presence: true # 役職
  # アソシエーション
  has_many :prototypes
  # has_many :comments
  has_many :comments, dependent: :destroy # userが削除された場合、commentsも削除
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  # ログインしていない状態で[]内アクションを行った場合、ログインページ(deviceのsigh_in)に遷移
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  private
  def configure_permitted_parameters
    # deviseのUserモデルにパラメーターを許可
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :profile, :occupation, :position])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    # Comment.create(comment_params)
    # redirect_to "/prototypes/#{comment.prototype.id}"  # コメントと結びつくプロトタイプの詳細画面に遷移する
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to prototype_path(@comment.prototype) # 今回の実装には関係ありませんが、このようにPrefixでパスを指定することが望ましいです。
    else
      @prototype = @comment.prototype
      @comments = @prototype.comments
      render "prototypes/show" # views/tweets/show.html.erbのファイルを参照しています。
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, prototype_id: params[:prototype_id])
  end
end

app/controllers/prototypes_controller.rb
class PrototypesController < ApplicationController
  before_action :set_prototype, only: [:edit, :show]
  before_action :move_to_index, except: [:index, :create, :show, :new, :destroy, :update]

  def index # 一覧表示
    @prototype = Prototype.new
    @prototypes = Prototype.all
  end

  def new # 生成
    # Prototypeモデルのインスタンス変数@prototypeを定義(生成)
    @prototype = Prototype.new
  end

  def create # 保存
    # Prototype.create(prototype_params)
    @prototype = Prototype.new(prototype_params)
    if @prototype.save
      # redirect_to root_path(@room)
      redirect_to root_path
    else
      render :new
    end

    def show # 詳細表示
      # @prototype = Prototype.find(params[:id])
      @comment = Comment.new
      @comments = @prototype.comments.includes(:user)
    end

    def edit # 編集
      # @prototype = Prototype.find(params[:id])
    end

    def update # 更新
      prototype = Prototype.find(params[:id])
      prototype.update(prototype_params)
      # 更新が成功した時、詳細ページへ遷移
      if prototype.save
        redirect_to prototype_path(prototype.id)
      # 更新が失敗した時、編集ページへ遷移
      else
        @prototype = Prototype.find(params[:id])
        render :edit
      end
    end

    def destroy # 削除
      prototype = Prototype.find(params[:id])
      prototype.destroy
      redirect_to root_path
    end

  end

  private
  def prototype_params
    params.require(:prototype).permit(:title, :catch_copy, :concept, :image).merge(user_id: current_user.id)
  end

  # edit・showが行われた時、beforeで実行
  def set_prototype
    @prototype = Prototype.find(params[:id])
  end

  def move_to_index
    # unless user_signed_in?
    # 投稿したprototypeのユーザーid と 自分のidが同じ・・・ではなかったら、indexへ遷移
    unless @prototype.user.id == current_user.id
      redirect_to action: :index
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    user = User.find(params[:id])
    @name = user.name # ユーザーの名前
    @prototypes = user.prototypes # ユーザーの投稿
    @profile = user.profile # ユーザーのプロフィール
    @occupation = user.occupation # ユーザーの所属
    @position = user.position # ユーザーの役職
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/prototypes_helper.rb
module PrototypesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<%# トップページのヘッダーとフッター %>
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>ProtoSpace</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap" rel="stylesheet">
  </head>

  <body>
    <header class="header">
      <div class="inner">
        <div class="nav">
          <div class="nav__left">
            <%= link_to image_tag("logo.png", class: :logo), root_path %>
          </div>
          <%# ログインしているときは以下を表示するようにしましょう %>
          <% if user_signed_in? %>
            <div class="nav__right">
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: :nav__logout %>
              <%= link_to "New Proto", new_prototype_path, class: :nav__btn %>
              <%# new_prototype_path %>
            </div>
          <%# // ログインしているときは上記を表示するようにしましょう %>
          <% else %>
          <%# ログインしていないときは以下を表示するようにしましょう %>
            <div class="nav__right">
              <%= link_to "ログイン", new_user_session_path, class: :nav__btn %>
              <%= link_to "新規登録", new_user_registration_path, class: :nav__btn %>
            </div>
          <%# // ログインしていないときは上記を表示するようにしましょう %>
          <% end %>
        </div>
      </div>
    </header>
    <%= yield %>
    <footer class="footer">
      <p class="copyright">Copyright © PROTO SPACE All rights reserved.</p>
    </footer>
  </body>
</html>

app/views/prototypes/_form.html.erb
<%# <%= form_with local: true do |f|%>
<%= form_with(model: @prototype, local: true) do |f|%>
  <div class="field">
    <%= f.label :title, "プロトタイプの名称" %><br />
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :catch_copy, "キャッチコピー" %><br />
    <%= f.text_area :catch_copy, class: :form__text %>
  </div>

  <div class="field">
    <%= f.label :concept, "コンセプト" %><br />
    <%= f.text_area :concept, class: :form__text %>
  </div>

  <div class="field">
    <%= f.label :image, "プロトタイプの画像" %><br />
    <%= f.file_field :image %>
  </div>

  <div class="actions">
    <%= f.submit "保存する", class: :form__btn  %>
  </div>
<% end %>

app/views/prototypes/_prototype.html.erb
<%# トップページの投稿表示一覧 %>
<div class="card">
  <%# <%= link_to image_tag("プロトタイプの画像", class: :card__img ), root_path%>
  <%= link_to image_tag(prototype.image, class: :card__img), prototype_path(prototype.id), method: :get if prototype.image.attached? %>
  <div class="card__body">
    <%# <%= link_to "プロトタイプのタイトル", root_path, class: :card__title%>
    <%= link_to prototype.title, prototype_path(prototype.id), method: :get, class: :card__title%>
    <p class="card__summary">
      <%# <%= "プロトタイプのキャッチコピー" %>
      <%= prototype.catch_copy %>
    </p>
    <%# <%= link_to "by プロトタイプの投稿者名", root_path, class: :card__user %>
    <%= link_to "by #{prototype.user.name}", user_path(prototype.user.id), class: :card__user %>
  </div>
</div>

app/views/prototypes/edit.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">プロトタイプ編集</h2>
      <%# 部分テンプレートでフォームを表示する %>
      <%= render partial: "form" %>
      <%# <%= render partial: "form", locals: { prototype: @prototype } %>
    </div>
  </div>
</div>

app/views/prototypes/index.html.erb
<%# トップページのメイン部分(body) %>
<main class="main">
  <div class="inner">
    <%# ログインしているときは以下を表示する %>
    <% if user_signed_in? %>
      <div class="greeting">
        <%= "こんにちは、" %>
        <%= link_to "#{current_user.name}さん", user_path(current_user.id), method: :get, class: :greeting__link %>
      </div>
    <%# // ログインしているときは上記を表示する %>
    <%# <% else %>
    <% end %>
    <div class="card__wrapper">
      <%# 投稿機能実装後、部分テンプレートでプロトタイプ投稿一覧を表示する %>
      <%= render partial: 'prototype', collection: @prototypes %>
    </div>
  </div>
</main>

app/views/prototypes/new.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">新規プロトタイプ投稿</h2>
        <%# 部分テンプレートでフォームを表示する %>
        <%= render partial: "form" %> <%#, locals: { tweet(変数): tweet(変数の中身) }  ←render先で変数を使用したいときはくっつける%>
    </div>
  </div>
</div>

app/views/prototypes/show.html.erb
<main class="main">
  <div class="inner">
    <div class="prototype__wrapper">
      <p class="prototype__hedding">
        <%# <%= "プロトタイプのタイトル"%>
        <%= @prototype.title %>
      </p>
      <%# <%= link_to "by プロトタイプの投稿者", root_path, class: :prototype__user %>
      <%= link_to "by #{@prototype.user.name}", user_path(@prototype.user.id), class: :prototype__user %>
      <%# プロトタイプの投稿者とログインしているユーザーが同じであれば以下を表示する %>
      <% if user_signed_in? && current_user.id == @prototype.user_id %>
        <div class="prototype__manage">
          <%= link_to "編集する", edit_prototype_path(@prototype.id), class: :prototype__btn %>
          <%= link_to "削除する", prototype_path(@prototype.id), method: :delete, class: :prototype__btn %>
        </div>
      <%# // プロトタイプの投稿者とログインしているユーザーが同じであれば上記を表示する %>
      <% end %>
      <div class="prototype__image">
        <%# <%= image_tag "プロトタイプの画像" %>
        <%= image_tag(@prototype.image, class: :card__img) if @prototype.image.attached? %>
      </div>
      <div class="prototype__body">
        <div class="prototype__detail">
          <p class="detail__title">キャッチコピー</p>
          <p class="detail__message">
            <%# <%= "プロトタイプのキャッチコピー" %>
            <%= @prototype.catch_copy %>
          </p>
        </div>
        <div class="prototype__detail">
          <p class="detail__title">コンセプト</p>
          <p class="detail__message">
            <%# <%= "プロトタイプのコンセプト" %>
            <%= @prototype.concept %>
          </p>
        </div>
      </div>
      <div class="prototype__comments">
        <% if user_signed_in? %>
        <%# ログインしているユーザーには以下のコメント投稿フォームを表示する %>
          <%# <%= form_with local: true do |f| %>
          <%= form_with model: [@prototype, @comment], local: true do |f| %>
            <div class="field">
              <%= f.label :text, "コメント" %><br />
              <%= f.text_field :text %>
            </div>
            <div class="actions">
              <%= f.submit "送信する", class: :form__btn %>
            </div>
          <% end %>
        <%# // ログインしているユーザーには上記を表示する %>
        <% end %>
        <ul class="comments_lists">
          <%# 投稿に紐づくコメントを一覧する処理を記述する %>
          <% if @comments %>
            <% @comments.each do |comment| %>
              <li class="comments_list">
                <%# <%= " コメントのテキスト " %>
                <%= comment.text %>
                <%# <%= link_to "（ ユーザー名 ）", root_path, class: :comment_user %>
                <%= link_to "（ #{comment.user.name} ）", user_path(comment.user.id), class: :comment_user %>
              </li>
            <% end %>
          <% end %>
          <%# // 投稿に紐づくコメントを一覧する処理を記述する %>
        </ul>
      </div>
    </div>
  </div>
</main>

app/views/users/show.html.erb
<div class="main">
  <div class="inner">
    <div class="user__wrapper">
      <h2 class="page-heading">
        <%= "#{@name}さんの情報"%>
      </h2>
      <table class="table">
        <tbody>
          <tr>
            <th class="table__col1">名前</th>
            <td class="table__col2"><%= @name %></td>
          </tr>
          <tr>
            <th class="table__col1">プロフィール</th>
            <td class="table__col2"><%= @profile %></td>
          </tr>
          <tr>
            <th class="table__col1">所属</th>
            <td class="table__col2"><%= @occupation %></td>
          </tr>
          <tr>
            <th class="table__col1">役職</th>
            <td class="table__col2"><%= @position %></td>
          </tr>
        </tbody>
      </table>
      <h2 class="page-heading">
        <%= "#{@name}さんのプロトタイプ"%>
      </h2>
      <div class="user__card">
        <%# 部分テンプレートでそのユーザーが投稿したプロトタイプ投稿一覧を表示する %>
        <%# メモ：prototypeディレクトリから持ってくる点に注意！！！！！！！！ %>
        <%= render partial: '/prototypes/prototype', collection: @prototypes %>
      </div>
    </div>
  </div>
</div>